### ISSUE TITLE
Server crash on startup

### ISSUE THREAD

**Issue by Farsinuce** [Darkhax-Minecraft/Dark-Paintings#10]
**Issue description:**
The server will not start.

**Server error log:**
[https://www.toptal.com/developers/hastebin/ayerizineh.sql](https://www.toptal.com/developers/hastebin/ayerizineh.sql)

**Work-around:**
Remove Dark Paintings from mods folder...

**Versions:**
DarkPaintings-Fabric-1.19-11.0.2.jar
Minecraft 1.19
Fabric Loader 0.14.8
Fabric API 0.57.0
Iris 2.0.4

Sorry, what am I doing wrong here?
Thank you in advance.

**Comment by Darkhax** [comment]
You did not install the Bookshelf mod. It's a required library. https://www.curseforge.com/minecraft/mc-mods/bookshelf

**Comment by Farsinuce** [comment]
You are right.
Sorry for this obvious mistake.

Thank you for your time.

Now I just hope that serilum has a fix for [his mod](https://github.com/ricksouth/serilum-mc-mods/issues/1002), so Dark Paintings can also cycle in 1.19.
