### ISSUE TITLE
Bookshelf dependency

### ISSUE THREAD

**Issue by Apceniy** [Darkhax-Minecraft/Dark-Paintings#14]
The mod requires Bookshelf to work, but it isn't specified in `fabric.mod.json`, causing crash without Fabric telling the user that there's another mod he needs to install. And it isn't mentioned explicitly on the Curseforge mod page too, the user has to either be aware of Relations tab on Curseforge and think about checking it, or someone else has to tell about it. This severely increases the amount of users not understanding why the mod doesn't work, which could impact the mod's popularity.

**Comment by Darkhax** [comment]
Thanks for letting me know. This should now be fixed on 1.18.2, 1.19.2, and 1.19.3. Please let me know if you have further issues.

**Comment by Apceniy** [comment]
I would also mention that dependency on the Curseforge mod page so users would notice it more likely, but it's up to you if you want this or not. Anyway, thanks for fixing the mod itself
