### ISSUE TITLE
Asset license?

### ISSUE THREAD

**Issue by enjarai** [Darkhax-Minecraft/Dark-Paintings#15]
Under what license are the assets of this mod published? The Curseforge and Modrinth page mention LGPL, but this is not reflected in the Github source.

I'm asking because I've been wanting to create a compatibility pack for my mod (https://github.com/enjarai/client-paintings) containing the paintings of this one. Would this be possible, or would you prefer I didn't either way?

**Comment by Darkhax** [comment]
Yes the assets in this mod are licensed under LGPL 2.1. While what you want to do is permitted by the license I would appreciate the opportunity to publish a compatibility pack myself like I have in the past with the [Paintings++ mod](https://legacy.curseforge.com/minecraft/texture-packs/dark-paintings-paintings-compat).

**Comment by enjarai** [comment]
Oh yea for sure, it'd be great if you could make it "officially" for lack of a better term. Be sure to check out the documentation of the resource pack format at https://github.com/enjarai/client-paintings#resource-pack-format, and do let me know if anything doesn't make sense or is poorly explained.

**Comment by Darkhax** [comment]
I finally had time to look into this today. The process was straight forward enough and I already have build uploading to [CurseForge](https://www.curseforge.com/minecraft/texture-packs/dark-paintings-client-paintings-compat). You can get it early here. [DarkPaintings-ClientPaintings-1.20.2-18.0.2.zip](https://github.com/Darkhax-Minecraft/Dark-Paintings/files/14531763/DarkPaintings-ClientPaintings-1.20.2-18.0.2.zip)

I tried to use your web based pack editor but it couldn't find the textures from my zip. I am guessing it's looking for them in a specific location. It may be cool to add a feature that can convert mod jars to compatibility packs so other mods with paintings can also be easily supported. You could probably even have your mod do this at runtime.
