### ISSUE TITLE
Modrinth Support

### ISSUE THREAD

**Issue by Ecorous** [Darkhax-Minecraft/Dark-Paintings#7]

**Comment by Darkhax** [comment]
I have no intentions of supporting Modrinth and do not want to see my projects hosted there. Please stop asking.

**Comment by K0-RR** [comment]
@Darkhax sorry to bother you, can you give us some information on why did you make this decision?

**Comment by Darkhax** [comment]
@RDKRACZ As someone who does modding as a full time job, deciding to support a new mod hosting platform is a very serious business decision. I do not have a good relation with the Modrinth team and they lack the trust necessary for me to support their project. 

Additionally, their team has been monetizing projects hosted on the platform but do not offer any revenue share or royalties to authors. They have been operating without these systems for over a year now so this does not seem to be an active priority for their team. I personally find the situation predatory and it is not something I want to endorse or be caught up in.

Furthermore, having random people spam my issue trackers, DMs, and other methods of contact about supporting their project does not help their credibility.
